import './globals.css'
import type { Metadata } from 'next'
import { publicSans } from './ui/fonts';
import { ClerkProvider } from "@clerk/nextjs";
import ToastProvider from '@/components/providers/toaster.provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en" className="scroll-smooth scroll-pt-10">
        <body className={`${publicSans.className} antialiased`}>
          <ToastProvider />
          {children}
          </body>
      </html>
    </ClerkProvider>
  )
}
